version: '3'
services:
  # This is database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admin
    ports:
      - '5432:5432'
